### ISSUE TITLE
EIGHT_CONNECTED enum error

### ISSUE THREAD

**Issue by Nicholas-Schaub** [usnistgov/WIPP-mask-labeling-plugin#3]
When running the mask labeling plugin in WIPP 3.0 and EIGHT_CONNECTED is selected, the job appears to complete in Argo but the logs show this error:

```bash
SEVERE: Error while labeling the image.
java.lang.IllegalArgumentException: No enum constant gov.nist.itl.ssd.wipp.masklabelingplugin.utils.Connectedness.EIGHT_CONNECTED
        at java.lang.Enum.valueOf(Enum.java:238)
        at gov.nist.itl.ssd.wipp.masklabelingplugin.utils.Connectedness.valueOf(Connectedness.java:3)
        at gov.nist.itl.ssd.wipp.masklabelingplugin.Main.main(Main.java:69)
```

The temporary job folder is empty, suggesting this error results in a failure of the plugin to label any masks in spite of the job reporting complete in Argo.

**Comment by MyleneSimon** [comment]
@mohamedOuladi Could you look into this?

**Comment by mohamedOuladi** [comment]
The docker image on the docker hub is not the most recent version and it does not match the code from the repo. I upgraded its version to "0.0.2".

**Comment by Nicholas-Schaub** [comment]
It works!
